
FROM debian:11 AS base

ENV REPO=https://github.com/slacgismo/gridlabd

ARG BRANCH=${BRANCH}
ARG DOCKER_COMMANDLINE=${DOCKER_COMMANDLINE}
RUN apt-get -q update -y \
    && apt-get install procps -y 
RUN apt-get install git -y
WORKDIR /opt/gridlabd/src
RUN git clone $REPO -b $BRANCH
WORKDIR /opt/gridlabd/src/gridlabd
RUN echo "INATALLATION COMMAND: $DOCKER_COMMANDLINE"
RUN $DOCKER_COMMANDLINE