#!/bin/bash

QUIET="-q"
STDOUT="/dev/null"
STDERR="/dev/null"

if [ $# -eq 0 ]; then
    /opt/gridlabd/bin/python3 -m pip freeze
    exit 0
fi

while [ $# -gt 0 ]; do
    if [ "$1" == "--requirements" -o "$1" == "-r" ]; then
        shift 1
        /opt/gridlabd/bin/python3 -m pip $QUIET install -r $1 
    elif [ "$1" == "--verbose" -o "$1" == "-v" ]; then
        QUIET=""
        STDERR="/dev/stderr"
        STDOUT="/dev/stdout"
    else
        /opt/gridlabd/bin/python3 -m pip freeze | grep $1 1>$STDOUT 2>$STDERR || /opt/gridlabd/bin/python3 -m pip $QUIET install $1 
        test "$(/opt/gridlabd/bin/python3 -m pip freeze | grep ^$1)" != "" || exit 1 
    fi
    shift 1
done
exit 0
